name: BetterGiveaways
version: ${project.version}
main: me.kartonixon.bettergiveaways.BetterGiveaways
api-version: 1.16
authors: [kartonixon]
description: Simple and easy to use Minecraft giveaway system

commands:
  giveaway:
    description: Joins the giveaway

permissions:
  bettergiveaways.manage:
    description: Allows starting/ending giveaways
    default: op